format = """
$username\
$hostname\
$directory\
$kubernetes\
$git_branch\
$git_state\
$cmd_duration\
$line_break\
$python\
$character"""

command_timeout = 10000

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
