format = """
$username\
$hostname\
$directory\
$kubernetes\
$git_branch\
$git_state\
$cmd_duration\
$line_break\
$python\
$character"""

command_timeout = 10000

[directory]
style = "#82aaff"

[character]
success_symbol = "[❯](#c792ea)"
error_symbol = "[❯](#ff5370)"
vimcmd_symbol = "[❮](#c3e88d)"

[git_branch]
format = "[$branch]($style) "
style = "#545454"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#545454"

[cmd_duration]
format = "[$duration]($style) "
style = "#ffcb6b"

[python]
format = "[$virtualenv]($style) "
style = "#545454"

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
